" Enable relative line numbers
set rnu

" Replace tabs for 2 spaces
set expandtab
set ts=2
set sw=2

" Enable syntax highlight
syntax enable

" Set new buffer position
set splitright
set splitbelow

" Show the current command
set showcmd

" Set file encoding
set encoding=utf8

" Load configuration modules
source ~/.vim/modules/colors.vim
source ~/.vim/modules/nerd-tree-highlight.vim

" Plugins
call plug#begin('~/.vim/plugged')
  " Nerd Tree
  Plug 'scrooloose/nerdtree'

  " Nerd Tree Highlight
  Plug 'https://github.com/tiagofumo/vim-nerdtree-syntax-highlight.git'

  " Dev Icons
  Plug 'https://github.com/ryanoasis/vim-devicons.git'
call plug#end()
