# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="breja"

# Disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load?
plugins=(z)

source $ZSH/oh-my-zsh.sh

# User configuration

# Use Vi keybindings
bindkey -v

# And keep the history search
bindkey '^R' history-incremental-search-backward

# Configure the PATH variable
export PATH=$PATH:/usr/local/bin

# For some reason I need this
export LC_ALL=en_US.UTF-8

# Source temporary configuration
if [ -f ~/.zshrc-temp ]; then
    source ~/.zshrc-temp
fi
