" Enable relative line numbers
set rnu

" Replace tabs for 2 spaces
set expandtab
set ts=2
set sw=2

" Enable syntax highlight
syntax enable

" Set new buffer position
set splitright
set splitbelow

" Show the current command
set showcmd

" Set file encoding
set encoding=utf8

" Load configuration modules
source ~/.vim/modules/colors.vim

" Plugins
call plug#begin('~/.vim/plugged')
  " Nerd Tree
  Plug 'scrooloose/nerdtree'
call plug#end()
