" Enable relative line numbers
set rnu

" Replace tabs for 2 spaces
set expandtab
set ts=2
set sw=2

" Disable line wrapping
set nowrap

" Enable syntax highlight
syntax enable

" Set new buffer position
set splitright
set splitbelow

" Show the current command
set showcmd

" Set file encoding
set encoding=utf8

" Load configuration modules
source ~/.vim/modules/colors.vim

source ~/.vim/modules/vimtex.vim

" Plugins
call plug#begin('~/.vim/plugged')
  " NERDTree
  Plug 'scrooloose/nerdtree'

  " vimtex
  Plug 'lervag/vimtex'
call plug#end()
